In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("yo")
df = pd.read_csv("train_input_MaPtRPJ.csv")
X = df.to_numpy()
df = pd.read_csv("train_output_xd4VV9Q.csv")
y = df.to_numpy()
print("taille des données:")
print("X:", X.shape)
print("Y:", y.shape)

df = pd.read_csv("test_input_5c0imze.csv")
Xtest = df.to_numpy()
print("test:", Xtest.shape)
print(y)
Xef=X[:,1:7]
Xef=np.hstack((Xef,X[:,8:15]))
Xef=np.hstack((Xef,X[:,16:23]))
Xef=np.hstack((Xef,X[:,24:25]))
Xid=X[:,0]

Xeftest=Xtest[:,1:7]
Xeftest=np.hstack((Xeftest,Xtest[:,8:15]))
Xeftest=np.hstack((Xeftest,Xtest[:,16:23]))
Xeftest=np.hstack((Xeftest,Xtest[:,24:25]))
Xidtest=Xtest[:,0]
print(Xeftest)

yo
taille des données:
X: (1837079, 25)
Y: (1837079, 2)
test: (1837080, 25)
[[      0      11]
 [      1      11]
 [      2      11]
 ...
 [1837076      12]
 [1837077      11]
 [1837078      11]]
[[2 3 6 ... 2 6 4]
 [3 1 1 ... 5 6 4]
 [2 4 6 ... 2 3 4]
 ...
 [1 6 3 ... 1 3 1]
 [1 2 4 ... 6 4 3]
 [4 5 1 ... 6 2 4]]


In [2]:
import pandas as pd
import numpy as np

from sklearn import neighbors, linear_model


import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from matplotlib.colors import ListedColormap
Xwd=Xef[0:700000,:]
ywd=y[0:700000,1]
Xwdid=Xid[0:700000]
ywdid=y[0:700000,0]
X_test=Xef[1000001:1005000]
y_test=y[1000001:1005000,1]
test_id=Xidtest
print(test_id)

[1837079 1837080 1837081 ... 3674156 3674157 3674158]


In [3]:
knn = neighbors.KNeighborsClassifier(metric='hamming')
knn_model = knn.fit(Xwd, ywd)

In [4]:
ypred=knn_model.predict(X_test)



In [5]:
Xpaire=[]
Ximpaire=[]
ypaire=[]
yimpaire=[]
nbpaire=0
nbimpaire=0
for i in range(700000):
    if(ywd[i]==1 or ywd[i]==3 or ywd[i]==5 or ywd[i]==7 or ywd[i]==9 or ywd[i]==11 or ywd[i]==13):
        yimpaire=np.hstack((yimpaire,ywd[i]))
        Ximpaire=np.hstack((Ximpaire,Xwd[i]))
        nbimpaire=nbimpaire+1
    else:
        ypaire=np.hstack((ypaire,ywd[i]))
        Xpaire=np.hstack((Xpaire,Xwd[i]))
        nbpaire=nbpaire+1

In [6]:
ypredpaire=[]
ypredimpaire=[]
paireid=[]
impaireid=[]
Xpredpaire=[]
Xpredimpaire=[]
nbpredpaire=0
nbpredimpaire=0
for i in range(ypred.size):
    if(ypred[i]==1 or ypred[i]==3 or ypred[i]==5 or ypred[i]==7 or ypred[i]==9 or ypred[i]==11 or ypred[i]==13):
        #ypredpaire=np.hstack((ypredpaire,y_test[i]))
        paireid=np.hstack((paireid,test_id[i]))
        Xpredpaire=np.hstack((Xpredpaire,X_test[i]))
        nbpredpaire=nbpredpaire+1
        
    else:
        #ypredimpaire=np.hstack((ypredimpaire,y_test[i]))
        impaireid=np.hstack((impaireid,test_id[i]))
        Xpredimpaire=np.hstack((Xpredimpaire,X_test[i]))
        nbpredimpaire=nbpredimpaire+1

In [7]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesRegressor, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
Xpaire2=Xpaire.reshape(nbpaire,21)
dtree = DecisionTreeClassifier(criterion='entropy',splitter='best', max_depth=8)
dtree.fit(Xpaire2, ypaire)
predictions = dtree.predict(Xpredpaire.reshape(nbpredpaire,21))

In [8]:
Ximpaire2=Ximpaire.reshape(nbimpaire,21)
dtree = DecisionTreeClassifier(criterion='entropy',splitter='best', max_depth=8)
dtree.fit(Ximpaire2, yimpaire)
predictionsim = dtree.predict(Xpredimpaire.reshape(nbpredimpaire,21))

In [9]:
kpaire=0
kimpaire=0
yfinal=[]
for i in range(1837079,1837079+predictions.size+predictionsim.size):
    if(kpaire!=paireid.size):
        if(paireid[kpaire]==i):   
            yfinal=np.hstack((yfinal,predictions[kpaire]))
            kpaire=kpaire+1
    if(kimpaire!=impaireid.size):
        if(impaireid[kimpaire]==i):
            yfinal=np.hstack((yfinal,predictionsim[kimpaire]))
            kimpaire=kimpaire+1

In [10]:
yfinal=yfinal.reshape(-1,1)
print(yfinal)

[[10.]
 [10.]
 [11.]
 ...
 [11.]
 [10.]
 [10.]]


In [11]:
test_id=test_id.reshape(-1,1)
print(test_id)

[[1837079]
 [1837080]
 [1837081]
 ...
 [3674156]
 [3674157]
 [3674158]]


In [16]:
def write_in_file(filename, ytest, start=1837079, finish=3674158):
    with open(filename, 'w') as writefile:
        count = start
        writefile.write("id,distance\n")
        while count <= finish:
            writefile.write(str(count) + "," + str(int(ytest[count - start])) + "\n")
            count += 1

In [19]:
yrendu=np.hstack((test_id[1000001:1005000],yfinal))
yrendu2=yrendu[:,1]

In [22]:
from sklearn.metrics import classification_report
#ytosubmit=yrendu2.reshape((len(yrendu2)),1)
#write_in_file("submit.csv",ytosubmit)
print(classification_report(y_test,yrendu2,zero_division=0))

              precision    recall  f1-score   support

           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00        17
           7       0.00      0.00      0.00        42
           8       0.00      0.00      0.00       167
           9       0.33      0.00      0.00       486
          10       0.47      0.86      0.61      1261
          11       0.71      0.94      0.81      1882
          12       0.37      0.07      0.12      1031
          13       0.00      0.00      0.00       108
          14       0.00      0.00      0.00         2

    accuracy                           0.59      4999
   macro avg       0.17      0.17      0.14      4999
weighted avg       0.50      0.59      0.49      4999



In [25]:
crfinal= confusion_matrix(y_test,yrendu2)
print(crfinal)

[[   0    0    0    0    0    0    1    0    0    0    0]
 [   0    0    0    0    0    0    1    1    0    0    0]
 [   0    0    0    0    0    0   14    2    1    0    0]
 [   0    0    0    0    0    0    0   42    0    0    0]
 [   0    0    0    0    0    0  143   11   13    0    0]
 [   0    0    0    0    0    1   33  449    3    0    0]
 [   0    0    0    0    1    0 1089   64  107    0    0]
 [   0    0    0    0    0    1  106 1767    8    0    0]
 [   0    0    0    0    0    0  915   39   77    0    0]
 [   0    0    0    0    0    1    4  103    0    0    0]
 [   0    0    0    0    0    0    2    0    0    0    0]]
